library(readr)
library(lavaan)

#### MRI SAMPLE 1 ####

MRI <- read_csv("MRI Sample 1 - 1st wave ED Data 5.1.23.csv")

MRI <- read_csv("MRI MEN self report Sample 1 - 1st wave ED Data 4.28.23.csv")

MRI <- read_csv("MRI self report Sample 2 - 2nd wave ED ALL MEN 5.1.23.csv")

MRI <- read_csv("MRI self report Sample 3 - Cues to Inf MEN 8.31.23.csv")

MRI <- read_csv("MRI WOMEN partner report Sample 1 - 1st wave ED Data 4.28.23.csv")

MRI <- read_csv("MRI partner report Sample 2 - 2nd wave ED ALL WOMEN 5.1.23.csv")

MRI <- read_csv("MRI self report Sample 3 - Cues to Inf WOMEN 8.31.23.csv")


MRI.One.Fact = 'MRI =~ M_MRI__1 + M_MRI__2 + M_MRI__3 + M_MRI__4 + M_MRI__5 + M_MRI__6 + M_MRI__7 + M_MRI__8 +
                        M_MRI__9 + M_MRI__10 + M_MRI__11 + M_MRI__12 + M_MRI__13 + M_MRI__14 + M_MRI__15 + 
                        M_MRI__16 + M_MRI__17 + M_MRI__18 + M_MRI__19 + M_MRI__20 + M_MRI__21 + M_MRI__22 + 
                        M_MRI__23 + M_MRI__24 + M_MRI__25 + M_MRI__26 + M_MRI__27 + M_MRI__28 + M_MRI__29 + 
                        M_MRI__30 + M_MRI__31 + M_MRI__32 + M_MRI__33 + M_MRI__34 + M_MRI__35 + M_MRI__36 + 
                        M_MRI__37 + M_MRI__38'



MRI.One.Fact = 'MRI =~ M_MRI_1 + M_MRI_2 + M_MRI_3 + M_MRI_4 + M_MRI_5 + M_MRI_6 + M_MRI_7 + M_MRI_8 +
                        M_MRI_9 + M_MRI_10 + M_MRI_11 + M_MRI_12 + M_MRI_13 + M_MRI_14 + M_MRI_15 + 
                        M_MRI_16 + M_MRI_17 + M_MRI_18 + M_MRI_19 + M_MRI_20 + M_MRI_21 + M_MRI_22 + 
                        M_MRI_23 + M_MRI_24 + M_MRI_25 + M_MRI_26 + M_MRI_27 + M_MRI_28 + M_MRI_29 + 
                        M_MRI_30 + M_MRI_31 + M_MRI_32 + M_MRI_33 + M_MRI_34 + M_MRI_35 + M_MRI_36 + 
                        M_MRI_37 + M_MRI_38'

MRI.One.Fact = 'MRI =~ W_MRI__1 + W_MRI__2 + W_MRI__3 + W_MRI__4 + W_MRI__5 + W_MRI__6 + W_MRI__7 + W_MRI__8 +
                        W_MRI__9 + W_MRI__10 + W_MRI__11 + W_MRI__12 + W_MRI__13 + W_MRI__14 + W_MRI__15 + 
                        W_MRI__16 + W_MRI__17 + W_MRI__18 + W_MRI__19 + W_MRI__20 + W_MRI__21 + W_MRI__22 + 
                        W_MRI__23 + W_MRI__24 + W_MRI__25 + W_MRI__26 + W_MRI__27 + W_MRI__28 + W_MRI__29 + 
                        W_MRI__30 + W_MRI__31 + W_MRI__32 + W_MRI__33 + W_MRI__34 + W_MRI__35 + W_MRI__36 + 
                        W_MRI__37 + W_MRI__38'

MRI.One.Fact = 'MRI =~ W_MRI_1 + W_MRI_2 + W_MRI_3 + W_MRI_4 + W_MRI_5 + W_MRI_6 + W_MRI_7 + W_MRI_8 +
                        W_MRI_9 + W_MRI_10 + W_MRI_11 + W_MRI_12 + W_MRI_13 + W_MRI_14 + W_MRI_15 + 
                        W_MRI_16 + W_MRI_17 + W_MRI_18 + W_MRI_19 + W_MRI_20 + W_MRI_21 + W_MRI_22 + 
                        W_MRI_23 + W_MRI_24 + W_MRI_25 + W_MRI_26 + W_MRI_27 + W_MRI_28 + W_MRI_29 + 
                        W_MRI_30 + W_MRI_31 + W_MRI_32 + W_MRI_33 + W_MRI_34 + W_MRI_35 + W_MRI_36 + 
                        W_MRI_37 + W_MRI_38'

# * Fit the model ----

MRI.One.Fact.Out = sem(MRI.One.Fact, data = MRI)

# * Get the summary ----

summary(MRI.One.Fact.Out, fit.measures = T, standardized = T, rsquare = T)

# * Inspect matrices ----

lavInspect(MRI.One.Fact.Out)

modindices(MRI.One.Fact.Out, sort = T)



# Invariant model

MRI.One.Fact.Out.Inv = sem(MRI.One.Fact, 
                         data = MRI,
                         meanstructure = T,
                         group ="Sex_Self",
                         group.equal = c('regressions','intercepts')) 

# Variant Model

MRI.One.Fact.Out.Var = sem(MRI.One.Fact, 
                         data = MRI,
                         meanstructure = T,
                         group ="Sex_Self") 

# * LRT ----

anova(MRI.One.Fact.Out.Inv, MRI.One.Fact.Out.Var)



# FITTING THREE FACTOR MODEL ----

# * Define the model ----

MRI.Two.Fact = 'cost =~ M_MRI__1 + M_MRI__2 + M_MRI__3 + M_MRI__4 + M_MRI__5 + M_MRI__6 + M_MRI__7 + 
                        M_MRI__8 + M_MRI__17 + M_MRI__18 + M_MRI__19 + M_MRI__20 + M_MRI__21 + M_MRI__22 +
                        M_MRI__23 + M_MRI__24 + M_MRI__25 + M_MRI__26 + M_MRI__27 + M_MRI__36 + M_MRI__37 + 
                        M_MRI__38
              benefit =~ M_MRI__9 + M_MRI__10 + M_MRI__11 + M_MRI__12 + M_MRI__ 13 + M_MRI__14 + M_MRI__15 + 
                          M_MRI__16 + M_MRI__28 + M_MRI__29 + M_MRI__30 + M_MRI__31 + M_MRI__32 + M_MRI__33 + 
                          M_MRI__34 + M_MRI__35'

###### MI Index Model for Sample 1 ##################################
MRI.Two.Fact = 'cost =~ M_MRI__1 + M_MRI__2 + M_MRI__3 + M_MRI__4 + M_MRI__5 + M_MRI__6 + M_MRI__7 + 
                        M_MRI__8 + M_MRI__17 + M_MRI__18 + M_MRI__19 + M_MRI__20 + M_MRI__21 + M_MRI__22 +
                        M_MRI__23 + M_MRI__24 + M_MRI__25 + M_MRI__26 + M_MRI__27 + M_MRI__36 + M_MRI__37 + 
                        M_MRI__38 + M_MRI__10 + M_MRI__12 + M_MRI__15 + M_MRI__31 + M_MRI__30 + M_MRI__29 +
                        M_MRI__28 + M_MRI__16 + M_MRI__33 + M_MRI__34 + M_MRI__35 + M_MRI__9
              benefit =~ M_MRI__9 + M_MRI__10 + M_MRI__11 + M_MRI__12 + M_MRI__ 13 + M_MRI__14 + M_MRI__15 + 
                          M_MRI__16 + M_MRI__28 + M_MRI__29 + M_MRI__30 + M_MRI__31 + M_MRI__32 + M_MRI__33 + 
                          M_MRI__34 + M_MRI__35 + M_MRI__7 + M_MRI__26 + M_MRI__17 + M_MRI__6 + M_MRI__38 + M_MRI__25'

MRI.Two.Fact = 'cost =~ W_MRI__1 + W_MRI__2 + W_MRI__3 + W_MRI__4 + W_MRI__5 + W_MRI__6 + W_MRI__7 + 
                        W_MRI__8 + W_MRI__17 + W_MRI__18 + W_MRI__19 + W_MRI__20 + W_MRI__21 + W_MRI__22 +
                        W_MRI__23 + W_MRI__24 + W_MRI__25 + W_MRI__26 + W_MRI__27 + W_MRI__36 + W_MRI__37 + 
                        W_MRI__38 + W_MRI__10 + W_MRI__15 + W_MRI__12 + W_MRI__35 + W_MRI__34 + W_MRI__31 + W_MRI__30
              benefit =~ W_MRI__9 + W_MRI__10 + W_MRI__11 + W_MRI__12 + W_MRI__ 13 + W_MRI__14 + W_MRI__15 + 
                          W_MRI__16 + W_MRI__28 + W_MRI__29 + W_MRI__30 + W_MRI__31 + W_MRI__32 + W_MRI__33 + 
                          W_MRI__34 + W_MRI__35 + W_MRI__7'

#####################################################################

###### MI Index Model for Sample 3 ##################################
MRI.Two.Fact = 'cost =~ M_MRI_1 + M_MRI_2 + M_MRI_3 + M_MRI_4 + M_MRI_5 + M_MRI_6 + M_MRI_7 + 
                        M_MRI_8 + M_MRI_17 + M_MRI_18 + M_MRI_19 + M_MRI_20 + M_MRI_21 + M_MRI_22 +
                        M_MRI_23 + M_MRI_24 + M_MRI_25 + M_MRI_26 + M_MRI_27 + M_MRI_36 + M_MRI_37 + 
                        M_MRI_38 + M_MRI_12 + M_MRI_35 + M_MRI_10 + M_MRI_16 + M_MRI_29
              benefit =~ M_MRI_9 + M_MRI_10 + M_MRI_11 + M_MRI_12 + M_MRI_13 + M_MRI_14 + M_MRI_15 + 
                          M_MRI_16 + M_MRI_28 + M_MRI_29 + M_MRI_30 + M_MRI_31 + M_MRI_32 + M_MRI_33 + 
                          M_MRI_34 + M_MRI_35 + M_MRI_7 + M_MRI_25 + M_MRI_26'

MRI.Two.Fact = 'cost =~ M_MRI_1 + M_MRI_2 + M_MRI_3 + M_MRI_4 + M_MRI_5 + M_MRI_6 + M_MRI_7 + 
                        M_MRI_8 + M_MRI_17 + M_MRI_18 + M_MRI_19 + M_MRI_20 + M_MRI_21 + M_MRI_22 +
                        M_MRI_23 + M_MRI_24 + M_MRI_25 + M_MRI_26 + M_MRI_27 + M_MRI_36 + M_MRI_37 + 
                        M_MRI_38 + M_MRI_10 + M_MRI_35 + M_MRI_13 + M_MRI_12
              benefit =~ M_MRI_9 + M_MRI_10 + M_MRI_11 + M_MRI_12 + M_MRI_13 + M_MRI_14 + M_MRI_15 + 
                          M_MRI_16 + M_MRI_28 + M_MRI_29 + M_MRI_30 + M_MRI_31 + M_MRI_32 + M_MRI_33 + 
                          M_MRI_34 + M_MRI_35'

#####################################################################

###### MI Index Model for Sample 2 ##################################
MRI.Two.Fact = 'cost =~ M_MRI_1 + M_MRI_2 + M_MRI_3 + M_MRI_4 + M_MRI_5 + M_MRI_6 + M_MRI_7 + 
                        M_MRI_8 + M_MRI_17 + M_MRI_18 + M_MRI_19 + M_MRI_20 + M_MRI_21 + M_MRI_22 +
                        M_MRI_23 + M_MRI_24 + M_MRI_25 + M_MRI_26 + M_MRI_27 + M_MRI_36 + M_MRI_37 + 
                        M_MRI_38 + M_MRI_10 + M_MRI_12 + M_MRI_29 + M_MRI_30 + M_MRI_13 + M_MRI_33 +
                        M_MRI_16 + M_MRI_35 
              benefit =~ M_MRI_9 + M_MRI_10 + M_MRI_11 + M_MRI_12 + M_MRI_13 + M_MRI_14 + M_MRI_15 + 
                          M_MRI_16 + M_MRI_28 + M_MRI_29 + M_MRI_30 + M_MRI_31 + M_MRI_32 + M_MRI_33 + 
                          M_MRI_34 + M_MRI_35 + M_MRI_6 + M_MRI_7 + M_MRI_19 + M_MRI_4 + M_MRI_25 + M_MRI_27 +
                          M_MRI_18 + M_MRI_37 + M_MRI_38 + M_MRI_8'

MRI.Two.Fact = 'cost =~ W_MRI_1 + W_MRI_2 + W_MRI_3 + W_MRI_4 + W_MRI_5 + W_MRI_6 + W_MRI_7 + 
                        W_MRI_8 + W_MRI_17 + W_MRI_18 + W_MRI_19 + W_MRI_20 + W_MRI_21 + W_MRI_22 +
                        W_MRI_23 + W_MRI_24 + W_MRI_25 + W_MRI_26 + W_MRI_27 + W_MRI_36 + W_MRI_37 + 
                        W_MRI_38 + W_MRI_10 + W_MRI_16 + W_MRI_35 + W_MRI_31 + W_MRI_12 + W_MRI_30
              benefit =~ W_MRI_9 + W_MRI_10 + W_MRI_11 + W_MRI_12 + W_MRI_13 + W_MRI_14 + W_MRI_15 + 
                          W_MRI_16 + W_MRI_28 + W_MRI_29 + W_MRI_30 + W_MRI_31 + W_MRI_32 + W_MRI_33 + 
                          W_MRI_34 + W_MRI_35 + W_MRI_7 + W_MRI_6 + W_MRI_23 + W_MRI_26 + W_MRI_19'

#####################################################################
MRI.Two.Fact = 'cost =~ M_MRI_1 + M_MRI_2 + M_MRI_3 + M_MRI_4 + M_MRI_5 + M_MRI_6 + M_MRI_7 + 
                        M_MRI_8 + M_MRI_17 + M_MRI_18 + M_MRI_19 + M_MRI_20 + M_MRI_21 + M_MRI_22 +
                        M_MRI_23 + M_MRI_24 + M_MRI_25 + M_MRI_26 + M_MRI_27 + M_MRI_36 + M_MRI_37 + 
                        M_MRI_38
              benefit =~ M_MRI_9 + M_MRI_10 + M_MRI_11 + M_MRI_12 + M_MRI_13 + M_MRI_14 + M_MRI_15 + 
                          M_MRI_16 + M_MRI_28 + M_MRI_29 + M_MRI_30 + M_MRI_31 + M_MRI_32 + M_MRI_33 + 
                          M_MRI_34 + M_MRI_35'

MRI.Two.Fact = 'cost =~ W_MRI__1 + W_MRI__2 + W_MRI__3 + W_MRI__4 + W_MRI__5 + W_MRI__6 + W_MRI__7 + 
                        W_MRI__8 + W_MRI__17 + W_MRI__18 + W_MRI__19 + W_MRI__20 + W_MRI__21 + W_MRI__22 +
                        W_MRI__23 + W_MRI__24 + W_MRI__25 + W_MRI__26 + W_MRI__27 + W_MRI__36 + W_MRI__37 + 
                        W_MRI__38
              benefit =~ W_MRI__9 + W_MRI__10 + W_MRI__11 + W_MRI__12 + W_MRI__ 13 + W_MRI__14 + W_MRI__15 + 
                          W_MRI__16 + W_MRI__28 + W_MRI__29 + W_MRI__30 + W_MRI__31 + W_MRI__32 + W_MRI__33 + 
                          W_MRI__34 + W_MRI__35'

MRI.Two.Fact = 'cost =~ W_MRI_1 + W_MRI_2 + W_MRI_3 + W_MRI_4 + W_MRI_5 + W_MRI_6 + W_MRI_7 + 
                        W_MRI_8 + W_MRI_17 + W_MRI_18 + W_MRI_19 + W_MRI_20 + W_MRI_21 + W_MRI_22 +
                        W_MRI_23 + W_MRI_24 + W_MRI_25 + W_MRI_26 + W_MRI_27 + W_MRI_36 + W_MRI_37 + 
                        W_MRI_38
              benefit =~ W_MRI_9 + W_MRI_10 + W_MRI_11 + W_MRI_12 + W_MRI_13 + W_MRI_14 + W_MRI_15 + 
                          W_MRI_16 + W_MRI_28 + W_MRI_29 + W_MRI_30 + W_MRI_31 + W_MRI_32 + W_MRI_33 + 
                          W_MRI_34 + W_MRI_35'

# * Fit the model ----

MRI.Two.Fact.Out = sem(MRI.Two.Fact, data = MRI)

# * Compare to one factor model ----

anova(MRI.One.Fact.Out, MRI.Two.Fact.Out)
# Better fitting model with three factors

# * Get the summary ----

summary(MRI.Two.Fact.Out, fit.measures = T, standardized = T, rsquare = T)

modindices(MRI.Two.Fact.Out, sort = T)

# Invariant model

MRI.Two.Fact.Out.Inv = sem(MRI.Two.Fact, 
                           data = MRI,
                           meanstructure = T,
                           group ="Sex_Self",
                           group.equal = c('regressions','intercepts')) 

# Variant Model

MRI.Two.Fact.Out.Var = sem(MRI.Two.Fact, 
                           data = MRI,
                           meanstructure = T,
                           group ="Sex_Self") 
# * LRT ----

anova(MRI.Two.Fact.Out.Inv, MRI.Two.Fact.Out.Var)

